-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cargo
(
    carid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cardes character varying(40) COLLATE pg_catalog."default" NOT NULL,
    carsld numeric(5, 2) NOT NULL,
    carestreg boolean NOT NULL,
    CONSTRAINT cargo_pkey PRIMARY KEY (carid)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    catid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    catnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    catestreg boolean NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (catid)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    ciuid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    regid smallint NOT NULL,
    ciunom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ciudes character varying(40) COLLATE pg_catalog."default",
    ciuestreg boolean NOT NULL,
    CONSTRAINT ciudad_pkey PRIMARY KEY (ciuid)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    cliid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    clinom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cliapepat character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cliapemat character varying(50) COLLATE pg_catalog."default" NOT NULL,
    clicorreo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    clidir character varying(100) COLLATE pg_catalog."default" NOT NULL,
    clilimcred integer NOT NULL,
    repid integer NOT NULL,
    cliestreg boolean NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (cliid)
);

CREATE TABLE IF NOT EXISTS public.creditos
(
    creid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    credes character varying(40) COLLATE pg_catalog."default",
    creestreg boolean NOT NULL,
    CONSTRAINT creditos_pkey PRIMARY KEY (creid)
);

CREATE TABLE IF NOT EXISTS public.factura
(
    facid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    repid integer NOT NULL,
    fabid integer NOT NULL,
    facprodes character varying(100) COLLATE pg_catalog."default",
    facimp integer NOT NULL,
    facanio integer NOT NULL,
    facmes integer NOT NULL,
    facdia integer NOT NULL,
    ciuid integer NOT NULL,
    facestreg boolean NOT NULL,
    CONSTRAINT factura_pkey PRIMARY KEY (facid)
);

CREATE TABLE IF NOT EXISTS public.detalle
(
    detid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    proid integer NOT NULL,
	facid integer NOT NULL,
    detprodes character varying(100) COLLATE pg_catalog."default",
    detcan integer NOT NULL,
    detestreg boolean NOT NULL,
    CONSTRAINT detalle_pkey PRIMARY KEY (detid)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    empid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    empnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    emptipo integer NOT NULL,
    empestreg boolean NOT NULL,
    CONSTRAINT empresa_pkey PRIMARY KEY (empid)
);

CREATE TABLE IF NOT EXISTS public.fabricante
(
    fabid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fabnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipoid integer NOT NULL,
    fabestreg boolean NOT NULL,
    CONSTRAINT fabricante_pkey PRIMARY KEY (fabid)
);

CREATE TABLE IF NOT EXISTS public.movimiento
(
    movid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    movnom character varying(20) COLLATE pg_catalog."default",
    movfecanio smallint,
    movfecmes smallint,
    movfecdia smallint,
    CONSTRAINT movimiento_pkey PRIMARY KEY (movid)
);

CREATE TABLE IF NOT EXISTS public.oficina
(
    ofid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ofrepid integer NOT NULL,
    empid integer NOT NULL,
    ofirepnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ofrepestreg boolean NOT NULL,
    CONSTRAINT oficina_pkey PRIMARY KEY (ofid)
);

CREATE TABLE IF NOT EXISTS public.oficina_representante
(
    ofrepid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ofid integer NOT NULL,
    ofirepnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ofirepestreg boolean NOT NULL,
    CONSTRAINT oficina_representante_pkey PRIMARY KEY (ofrepid),
    UNIQUE (ofid)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    proid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fabid integer NOT NULL,
    prodes character varying(100) COLLATE pg_catalog."default" NOT NULL,
    propre numeric(10, 2) NOT NULL,
    prosto integer NOT NULL,
    catid integer NOT NULL,
    prounimed character varying(3) COLLATE pg_catalog."default" NOT NULL,
    proestreg boolean NOT NULL,
    CONSTRAINT producto_pkey PRIMARY KEY (proid)
);

CREATE TABLE IF NOT EXISTS public.region
(
    regid smallint NOT NULL,
    regnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    regdes character varying(40) COLLATE pg_catalog."default",
    regestreg boolean NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (regid)
);

CREATE TABLE IF NOT EXISTS public.rep_venta
(
    repid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    carid integer NOT NULL,
    repnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    reped integer,
    ofid integer NOT NULL,
    repcar character varying(50) COLLATE pg_catalog."default" NOT NULL,
    repcon integer NOT NULL,
    repcuo integer NOT NULL,
    repvenreal integer NOT NULL,
    repestreg boolean NOT NULL,
    CONSTRAINT rep_venta_pkey PRIMARY KEY (repid)
);

CREATE TABLE IF NOT EXISTS public.rol_usuario
(
    rolid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rolnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    roldes character varying(50) COLLATE pg_catalog."default",
    rolestreg boolean NOT NULL,
    CONSTRAINT rol_usuario_pkey PRIMARY KEY (rolid)
);

CREATE TABLE IF NOT EXISTS public.tipo
(
    tipoid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tiponom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipoestreg boolean NOT NULL,
    CONSTRAINT tipo_pkey PRIMARY KEY (tipoid)
);

CREATE TABLE IF NOT EXISTS public.unidad_medida
(
    uniid character varying(3) COLLATE pg_catalog."default" NOT NULL,
    uninom character varying(15) COLLATE pg_catalog."default" NOT NULL,
    uniestreg boolean NOT NULL,
    CONSTRAINT unidad_medida_pkey PRIMARY KEY (uniid)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    usuid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    rolid integer NOT NULL,
    creid integer NOT NULL,
    usunom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    usucrefecanio smallint,
    usucrefecmes smallint,
    usucrefecdia smallint,
    usuestreg boolean NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (usuid)
);

ALTER TABLE IF EXISTS public.ciudad
    ADD CONSTRAINT ciudad_regid_fkey FOREIGN KEY (regid)
    REFERENCES public.region (regid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_repid_fkey FOREIGN KEY (repid)
    REFERENCES public.rep_venta (repid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_cliid_fkey FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_proid_fkey FOREIGN KEY (proid)
    REFERENCES public.producto (proid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_facid_fkey FOREIGN KEY (facid)
    REFERENCES public.factura (facid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT empresa_emptipo_fkey FOREIGN KEY (emptipo)
    REFERENCES public.tipo (tipoid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fabricante
    ADD CONSTRAINT fabricante_tipoid_fkey FOREIGN KEY (tipoid)
    REFERENCES public.tipo (tipoid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_ciuid_fkey FOREIGN KEY (ciuid)
    REFERENCES public.ciudad (ciuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_cliid_fkey FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_fabid_fkey FOREIGN KEY (fabid)
    REFERENCES public.fabricante (fabid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_repid_fkey FOREIGN KEY (repid)
    REFERENCES public.rep_venta (repid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento
    ADD CONSTRAINT movimiento_cliid_fkey FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.oficina
    ADD CONSTRAINT oficina_empid_fkey FOREIGN KEY (empid)
    REFERENCES public.empresa (empid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.oficina_representante
    ADD FOREIGN KEY (ofid)
    REFERENCES public.oficina (ofid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_catid_fkey FOREIGN KEY (catid)
    REFERENCES public.categoria (catid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_fabid_fkey FOREIGN KEY (fabid)
    REFERENCES public.fabricante (fabid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_prounimed_fkey FOREIGN KEY (prounimed)
    REFERENCES public.unidad_medida (uniid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rep_venta
    ADD CONSTRAINT rep_venta_carid_fkey FOREIGN KEY (carid)
    REFERENCES public.cargo (carid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rep_venta
    ADD CONSTRAINT rep_venta_ofid_fkey FOREIGN KEY (ofid)
    REFERENCES public.oficina (ofid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_cliid_fkey FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_creid_fkey FOREIGN KEY (creid)
    REFERENCES public.creditos (creid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_rolid_fkey FOREIGN KEY (rolid)
    REFERENCES public.rol_usuario (rolid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;