-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cargo
(
    carid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    carnom character varying(20) NOT NULL,
    cardes character varying(40) COLLATE pg_catalog."default" NOT NULL,
    carsue numeric(7, 2) NOT NULL,
    carestreg CHAR(1) NOT NULL CHECK(carestreg IN ('A', 'I', 'E')),
    CONSTRAINT cargo_pkey PRIMARY KEY (carid)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    catid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    catnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    catestreg CHAR(1) NOT NULL CHECK(catestreg IN ('A', 'I', 'E')),
    CONSTRAINT categoria_pkey PRIMARY KEY (catid)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    ciuid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    regid smallint NOT NULL,
    ciunom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ciudes character varying(40) COLLATE pg_catalog."default",
    ciuestreg CHAR(1) NOT NULL CHECK(ciuestreg IN ('A', 'I', 'E')),
    CONSTRAINT ciudad_pkey PRIMARY KEY (ciuid)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    cliid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    repid integer NOT NULL,
    creid integer NOT NULL,
    clinom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cliapepat character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cliapemat character varying(50) COLLATE pg_catalog."default" NOT NULL,
    clicor character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cliestreg CHAR(1) NOT NULL CHECK(cliestreg IN ('A', 'I', 'E')),
    CONSTRAINT cliente_pkey PRIMARY KEY (cliid)
);

CREATE TABLE IF NOT EXISTS public.creditos
(
    creid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    crenom character varying(40) NOT NULL,
    credes character varying(200) COLLATE pg_catalog."default",
    creestreg CHAR(1) NOT NULL CHECK (creestreg IN ('A', 'I', 'E')),
    CONSTRAINT creditos_pkey PRIMARY KEY (creid)
);

CREATE TABLE IF NOT EXISTS public.detalle
(
    detid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    proid integer NOT NULL,
    facid integer NOT NULL,
    detcan integer NOT NULL,
    detestreg CHAR(1) NOT NULL CHECK (detestreg IN ('A', 'I', 'E')),
    CONSTRAINT detalle_pkey PRIMARY KEY (detid)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    empid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    empnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    emptip integer NOT NULL,
    empestreg CHAR(1) NOT NULL CHECK (empestreg IN ('A', 'I', 'E')),
    CONSTRAINT empresa_pkey PRIMARY KEY (empid)
);

CREATE TABLE IF NOT EXISTS public.fabricante
(
    fabid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fabnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipid integer NOT NULL,
    fabestreg CHAR(1) NOT NULL CHECK (fabestreg IN ('A', 'I', 'E')),
    CONSTRAINT fabricante_pkey PRIMARY KEY (fabid)
);

CREATE TABLE IF NOT EXISTS public.factura_cabecera
(
    facid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    repid integer NOT NULL,
    ciuid integer NOT NULL,
    facfec date NOT NULL,
    facestreg CHAR(1) NOT NULL CHECK (facestreg IN ('A', 'I', 'E')),
    CONSTRAINT factura_pkey PRIMARY KEY (facid)
);

CREATE TABLE IF NOT EXISTS public.oficina
(
    ofiid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    empid integer NOT NULL,
    ofinom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ofirepestreg CHAR(1) NOT NULL CHECK (ofirepestreg IN ('A', 'I', 'E')),
    CONSTRAINT oficina_pkey PRIMARY KEY (ofiid)
);

CREATE TABLE IF NOT EXISTS public.oficina_representante
(
    ofirepid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ofiid integer NOT NULL,
    ofirepnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ofirepestreg CHAR(1) NOT NULL CHECK (ofirepestreg IN ('A', 'I', 'E')),
    CONSTRAINT oficina_representante_pkey PRIMARY KEY (ofirepid),
    CONSTRAINT oficina_representante_ofiid_key UNIQUE (ofiid)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    proid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fabid integer NOT NULL,
    pronom character varying(200),
    prodes character varying(300) COLLATE pg_catalog."default" NOT NULL,
    propre numeric(10, 2) NOT NULL,
    prosto integer NOT NULL,
    catid integer NOT NULL,
    prounimed character varying(3) COLLATE pg_catalog."default" NOT NULL,
    proestreg CHAR(1) NOT NULL CHECK (proestreg IN ('A', 'I', 'E')),
    CONSTRAINT producto_pkey PRIMARY KEY (proid)
);

CREATE TABLE IF NOT EXISTS public.region
(
    regid smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    regnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    regdes character varying(40) COLLATE pg_catalog."default",
    regestreg CHAR(1) NOT NULL CHECK (regestreg IN ('A', 'I', 'E')),
    CONSTRAINT region_pkey PRIMARY KEY (regid)
);

CREATE TABLE IF NOT EXISTS public.rep_venta
(
    repid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    carid integer NOT NULL,
    repnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    repapepat character varying(100) NOT NULL,
    repapemat character varying(100) NOT NULL,
    repfecnac date,
    ofiid integer NOT NULL,
    repcon date NOT NULL,
    repcuo integer NOT NULL,
    repven integer NOT NULL,
    repestreg CHAR(1) NOT NULL CHECK (repestreg IN ('A', 'I', 'E')),
    CONSTRAINT rep_venta_pkey PRIMARY KEY (repid)
);

CREATE TABLE IF NOT EXISTS public.tipo_empresa
(
    tipid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tipnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipestreg CHAR(1) NOT NULL CHECK (tipestreg IN ('A', 'I', 'E')),
    CONSTRAINT tipo_pkey PRIMARY KEY (tipid)
);

CREATE TABLE IF NOT EXISTS public.unidad_medida
(
    uniid character varying(3) COLLATE pg_catalog."default" NOT NULL,
    uninom character varying(15) COLLATE pg_catalog."default" NOT NULL,
    uniestreg CHAR(1) NOT NULL CHECK (uniestreg IN ('A', 'I', 'E')),
    CONSTRAINT unidad_medida_pkey PRIMARY KEY (uniid)
);

CREATE TABLE IF NOT EXISTS public.direccion
(
    dirid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    calid integer NOT NULL,
    dircalnum character varying(5) NOT NULL,
    barid integer NOT NULL,
    direstreg CHAR(1) NOT NULL CHECK (direstreg IN ('A', 'I', 'E')),
    PRIMARY KEY (dirid)
);

CREATE TABLE IF NOT EXISTS public.calle
(
    calid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    calnom character varying(100) NOT NULL,
    caldes character varying(200),
    calestreg CHAR(1) NOT NULL CHECK (calestreg IN ('A', 'I', 'E')),
    PRIMARY KEY (calid)
);

CREATE TABLE IF NOT EXISTS public.barrio
(
    barid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    barnom character varying(50) NOT NULL,
    bardes character varying(100),
    barestreg CHAR(1) NOT NULL CHECK (barestreg IN ('A', 'I', 'E')),
    PRIMARY KEY (barid)
);

ALTER TABLE IF EXISTS public.ciudad
    ADD CONSTRAINT ciudad_regid_fkey FOREIGN KEY (regid)
    REFERENCES public.region (regid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cliente
    ADD FOREIGN KEY (repid)
    REFERENCES public.rep_venta (repid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cliente
    ADD FOREIGN KEY (creid)
    REFERENCES public.creditos (creid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_facid_fkey FOREIGN KEY (facid)
    REFERENCES public.factura_cabecera (facid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_proid_fkey FOREIGN KEY (proid)
    REFERENCES public.producto (proid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT empresa_emptip_fkey FOREIGN KEY (emptip)
    REFERENCES public.tipo_empresa (tipid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fabricante
    ADD CONSTRAINT fabricante_tipid_fkey FOREIGN KEY (tipid)
    REFERENCES public.tipo_empresa (tipid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura_cabecera
    ADD CONSTRAINT factura_ciuid_fkey FOREIGN KEY (ciuid)
    REFERENCES public.ciudad (ciuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura_cabecera
    ADD CONSTRAINT factura_cliid_fkey FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura_cabecera
    ADD CONSTRAINT factura_repid_fkey FOREIGN KEY (repid)
    REFERENCES public.rep_venta (repid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.oficina
    ADD CONSTRAINT oficina_empid_fkey FOREIGN KEY (empid)
    REFERENCES public.empresa (empid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.oficina_representante
    ADD CONSTRAINT oficina_representante_ofiid_fkey FOREIGN KEY (ofiid)
    REFERENCES public.oficina (ofiid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS oficina_representante_ofiid_key
    ON public.oficina_representante(ofiid);


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_catid_fkey FOREIGN KEY (catid)
    REFERENCES public.categoria (catid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_fabid_fkey FOREIGN KEY (fabid)
    REFERENCES public.fabricante (fabid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_prounimed_fkey FOREIGN KEY (prounimed)
    REFERENCES public.unidad_medida (uniid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rep_venta
    ADD CONSTRAINT rep_venta_carid_fkey FOREIGN KEY (carid)
    REFERENCES public.cargo (carid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rep_venta
    ADD CONSTRAINT rep_venta_ofiid_fkey FOREIGN KEY (ofiid)
    REFERENCES public.oficina (ofiid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direccion
    ADD FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.direccion
    ADD FOREIGN KEY (calid)
    REFERENCES public.calle (calid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.direccion
    ADD FOREIGN KEY (barid)
    REFERENCES public.barrio (barid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;