-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cargo
(
    carid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CarNom" character varying(20) NOT NULL,
    cardes character varying(40) COLLATE pg_catalog."default" NOT NULL,
    carsue numeric(5, 2) NOT NULL,
    carestreg "char" NOT NULL,
    CONSTRAINT cargo_pkey PRIMARY KEY (carid)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    catid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    catnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    catestreg "char" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (catid)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    ciuid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    regid smallint NOT NULL,
    ciunom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ciudes character varying(40) COLLATE pg_catalog."default",
    ciuestreg "char" NOT NULL,
    CONSTRAINT ciudad_pkey PRIMARY KEY (ciuid)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    cliid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    repid integer NOT NULL,
    "creId" integer NOT NULL,
    clinom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cliapepat "char" COLLATE pg_catalog."default" NOT NULL,
    cliapemat character varying(50) COLLATE pg_catalog."default" NOT NULL,
    clicor character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cliestreg boolean NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (cliid),
    UNIQUE ("creId")
);

CREATE TABLE IF NOT EXISTS public.creditos
(
    creid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "creNom" character varying(40) NOT NULL,
    credes character varying(200) COLLATE pg_catalog."default",
    creestreg "char" NOT NULL,
    CONSTRAINT creditos_pkey PRIMARY KEY (creid)
);

CREATE TABLE IF NOT EXISTS public.detalle
(
    detid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    proid integer NOT NULL,
    facid integer NOT NULL,
    detcan integer NOT NULL,
    detestreg "char" NOT NULL,
    CONSTRAINT detalle_pkey PRIMARY KEY (detid)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    empid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    empnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    emptip integer NOT NULL,
    empestreg "char" NOT NULL,
    CONSTRAINT empresa_pkey PRIMARY KEY (empid)
);

CREATE TABLE IF NOT EXISTS public.fabricante
(
    fabid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fabnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipid integer NOT NULL,
    fabestreg "char" NOT NULL,
    CONSTRAINT fabricante_pkey PRIMARY KEY (fabid)
);

CREATE TABLE IF NOT EXISTS public.factura_cabecera
(
    facid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cliid integer NOT NULL,
    repid integer NOT NULL,
    ciuid integer NOT NULL,
    "facFec" date NOT NULL,
    facestreg "char" NOT NULL,
    CONSTRAINT factura_pkey PRIMARY KEY (facid)
);

CREATE TABLE IF NOT EXISTS public.oficina
(
    ofiid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    empid integer NOT NULL,
    ofinom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ofirepestreg "char" NOT NULL,
    CONSTRAINT oficina_pkey PRIMARY KEY (ofiid)
);

CREATE TABLE IF NOT EXISTS public.oficina_representante
(
    ofirepid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ofiid integer NOT NULL,
    ofirepnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ofirepestreg "char" NOT NULL,
    CONSTRAINT oficina_representante_pkey PRIMARY KEY (ofirepid),
    CONSTRAINT oficina_representante_ofiid_key UNIQUE (ofiid)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    proid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fabid integer NOT NULL,
    "ProNom" character varying(200),
    prodes character varying(300) COLLATE pg_catalog."default" NOT NULL,
    propre numeric(10, 2) NOT NULL,
    prosto integer NOT NULL,
    catid integer NOT NULL,
    prounimed character varying(3) COLLATE pg_catalog."default" NOT NULL,
    proestreg "char" NOT NULL,
    CONSTRAINT producto_pkey PRIMARY KEY (proid)
);

CREATE TABLE IF NOT EXISTS public.region
(
    regid smallint NOT NULL,
    regnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    regdes character varying(40) COLLATE pg_catalog."default",
    regestreg "char" NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (regid)
);

CREATE TABLE IF NOT EXISTS public.rep_venta
(
    repid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    carid integer NOT NULL,
    repnom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "repApePat" character varying(100) NOT NULL,
    "repApeMat" character varying(100) NOT NULL,
    "repFecNac" date,
    ofiid integer NOT NULL,
    repcon integer NOT NULL,
    repcuo integer NOT NULL,
    repven integer NOT NULL,
    repestreg "char" NOT NULL,
    CONSTRAINT rep_venta_pkey PRIMARY KEY (repid)
);

CREATE TABLE IF NOT EXISTS public.tipo
(
    tipid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tipnom character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipestreg "char" NOT NULL,
    CONSTRAINT tipo_pkey PRIMARY KEY (tipid)
);

CREATE TABLE IF NOT EXISTS public.unidad_medida
(
    uniid character varying(3) COLLATE pg_catalog."default" NOT NULL,
    uninom character varying(15) COLLATE pg_catalog."default" NOT NULL,
    uniestreg "char" NOT NULL,
    CONSTRAINT unidad_medida_pkey PRIMARY KEY (uniid)
);

CREATE TABLE IF NOT EXISTS public.direccion
(
    "DirId" integer NOT NULL,
    "CliId" integer NOT NULL,
    "CalId" integer NOT NULL,
    "DirCalNum" character varying(5) NOT NULL,
    "BarId" "char" NOT NULL,
    "DirEstReg" boolean NOT NULL,
    PRIMARY KEY ("DirId")
);

CREATE TABLE IF NOT EXISTS public.calle
(
    "CalId" integer NOT NULL,
    "CalNom" character varying(100) NOT NULL,
    "CalDes" character varying(200),
    "CalEstReg" "char" NOT NULL,
    PRIMARY KEY ("CalId")
);

CREATE TABLE IF NOT EXISTS public.barrio
(
    "BarId" integer NOT NULL,
    "BarNom" character varying(50) NOT NULL,
    "BarDes" character varying(100),
    "BarEstReg" "char" NOT NULL,
    PRIMARY KEY ("BarId")
);

ALTER TABLE IF EXISTS public.ciudad
    ADD CONSTRAINT ciudad_regid_fkey FOREIGN KEY (regid)
    REFERENCES public.region (regid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cliente
    ADD FOREIGN KEY (repid)
    REFERENCES public.rep_venta (repid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cliente
    ADD FOREIGN KEY ("creId")
    REFERENCES public.creditos (creid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_facid_fkey FOREIGN KEY (facid)
    REFERENCES public.factura_cabecera (facid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle
    ADD CONSTRAINT detalle_proid_fkey FOREIGN KEY (proid)
    REFERENCES public.producto (proid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle
    ADD FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT empresa_emptip_fkey FOREIGN KEY (emptip)
    REFERENCES public.tipo (tipid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fabricante
    ADD CONSTRAINT fabricante_tipid_fkey FOREIGN KEY (tipid)
    REFERENCES public.tipo (tipid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura_cabecera
    ADD CONSTRAINT factura_ciuid_fkey FOREIGN KEY (ciuid)
    REFERENCES public.ciudad (ciuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura_cabecera
    ADD CONSTRAINT factura_cliid_fkey FOREIGN KEY (cliid)
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura_cabecera
    ADD CONSTRAINT factura_repid_fkey FOREIGN KEY (repid)
    REFERENCES public.rep_venta (repid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.oficina
    ADD CONSTRAINT oficina_empid_fkey FOREIGN KEY (empid)
    REFERENCES public.empresa (empid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.oficina_representante
    ADD CONSTRAINT oficina_representante_ofiid_fkey FOREIGN KEY (ofiid)
    REFERENCES public.oficina (ofiid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS oficina_representante_ofiid_key
    ON public.oficina_representante(ofiid);


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_catid_fkey FOREIGN KEY (catid)
    REFERENCES public.categoria (catid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_fabid_fkey FOREIGN KEY (fabid)
    REFERENCES public.fabricante (fabid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_prounimed_fkey FOREIGN KEY (prounimed)
    REFERENCES public.unidad_medida (uniid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rep_venta
    ADD CONSTRAINT rep_venta_carid_fkey FOREIGN KEY (carid)
    REFERENCES public.cargo (carid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rep_venta
    ADD CONSTRAINT rep_venta_ofiid_fkey FOREIGN KEY (ofiid)
    REFERENCES public.oficina (ofiid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direccion
    ADD FOREIGN KEY ("CliId")
    REFERENCES public.cliente (cliid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.direccion
    ADD FOREIGN KEY ("CalId")
    REFERENCES public.calle ("CalId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.direccion
    ADD FOREIGN KEY ("BarId")
    REFERENCES public.barrio ("BarId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;